name: Deploy to GitHub Pages

on:
  # Desencadenar el workflow cada vez que hagas push a la rama `main`
  push:
    branches: [main]
  # Permite ejecutar el workflow manualmente desde la pestaña Actions en GitHub
  workflow_dispatch:

# Permisos necesarios para clonar el repositorio y desplegar en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # Especifica la versión de pnpm que uses

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Instalar dependencias
        run: pnpm install

      - name: Construir el proyecto
        run: pnpm run build

      - name: Subir artefactos de la construcción
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
